<?php

namespace App\Services\AI;

class ThumbnailConceptGenerator
{
    private NicheTemplateService $nicheTemplateService;
    private SystemInstructionBuilder $systemInstructionBuilder;

    public function __construct(
        NicheTemplateService $nicheTemplateService,
        SystemInstructionBuilder $systemInstructionBuilder
    ) {
        $this->nicheTemplateService = $nicheTemplateService;
        $this->systemInstructionBuilder = $systemInstructionBuilder;
    }

    /**
     * Generate detailed thumbnail concept
     * Implements logic from source function e1
     */
    public function generate(string $niche, string $country, string $title): string
    {
        $template = $this->nicheTemplateService->getTemplate($niche);
        $systemInstruction = $this->systemInstructionBuilder->buildWithUniqueness();
        
        $styleGuidance = "";
        if ($template && isset($template['thumbnailStyle'])) {
            $styleGuidance = "**THUMBNAIL STYLE GUIDANCE:**\n" . $template['thumbnailStyle'];
        }

        return <<<PROMPT
{$systemInstruction}

**TASK: GENERATE A HIGH-CTR THUMBNAIL CONCEPT**

Niche: {$niche}
Country: {$country}
Title: "{$title}"

{$styleGuidance}

**REQUIREMENTS:**
1. **Visual Composition**: Describe a specific, dramatic scene to be generated by AI (Midjourney/DALL-E 3).
2. **People**: Include 2-3 people in frame.
   - Describe their exact emotions (fear, tears, shock, determination).
   - Use high-contrast lighting to emphasize faces.
3. **Setting**: Ground the scene in a specific location relevant to the title and niche.
4. **Technical Specs**:
   - Photorealistic, 8K, cinematic lighting
   - 85mm Prime lens, f/1.8 aperture (bokeh background)
   - 16:9 aspect ratio
   - High dynamic range (HDR)
5. **No Text**: Do not include text in the image itself (unless specified for sign/document).

**OUTPUT SCHEMA (MANDATORY JSON):**
{
  "thumbnailConcept": "A detailed 400-word prompt describing the scene, characters, lighting, and camera settings..."
}

Output ONLY valid JSON.
PROMPT;
    }

    /**
     * Generate thumbnail from Bible blueprint
     * Implements logic from source function t1
     */
    public function generateFromBlueprint(
        string $title,
        string $niche,
        string $country,
        array $bible,
        string $firstChapterSummary
    ): string {
        $template = $this->nicheTemplateService->getTemplate($niche);
        $systemInstruction = $this->systemInstructionBuilder->buildWithUniqueness();
        
        $charDescriptions = [];
        foreach ($bible['characters'] ?? [] as $char) {
            $charDescriptions[] = "- **{$char['name']}**: {$char['appearance']}, role: {$char['role']}";
        }
        $charactersStr = implode("\n", $charDescriptions);

        $styleGuidance = "";
        if ($template && isset($template['thumbnailStyle'])) {
            $styleGuidance = "**THUMBNAIL STYLE GUIDANCE:**\n" . $template['thumbnailStyle'];
        }

        return <<<PROMPT
{$systemInstruction}

**TASK: GENERATE THUMBNAIL CONCEPT FROM STORY BLUEPRINT**

Title: "{$title}"
Niche: {$niche}
Country: {$country}

**STORY CONTEXT:**
First Chapter Summary: {$firstChapterSummary}

**CHARACTERS (USE AS REFERENCE):**
{$charactersStr}

{$styleGuidance}

**REQUIREMENTS:**
1. **Scene Selection**: Choose the most dramatic, clickable moment from the first chapter or the core conflict.
2. **Character Accuracy**: Use the provided character descriptions to ensure visual consistency.
3. **Emotion**: Focus on high-stakes emotion (betrayal, discovery, fear).
4. **Technical Specs**: Photorealistic, 8K, cinematic 16:9, 85mm lens.

**OUTPUT SCHEMA (MANDATORY JSON):**
{
  "thumbnailConcept": "Detailed 400-word prompt..."
}

Output ONLY valid JSON.
PROMPT;
    }
}
